remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme

title: XY
description: Lorem ipsum
show_downloads: False
navigation:
  - title: Home
    url: /
  - title: Setup
    url: setup
  - title: Test
    url: test
